// THIS FILE IS AUTOGENERATED from the parameters in config.json. Do not edit it.
// If you want to change something about how it's generated, look at library/asset_builder.ts.

import { TypesafeLoader } from "../library/typesafe_loader";

export type AssetType =
  | "Image"
  | "TileMap"
  | "TileWorld"
  | "Audio"
  | "Spritesheet"
  | "Animation"

export type AssetName = keyof typeof AssetsToLoad
export type AssetPath = 
  | "bookshelf.png"
  | "credits/credits.gif"
  | "dialog.png"
  | "dialog_box.png"
  | "interactions.json"
  | "loop1.mp3"
  | "loop2.mp3"
  | "manifest.json"
  | "map.json"
  | "miranda.png"
  | "miranda_portrait.png"
  | "music/credits.mp3"
  | "music/mystery loop 1.mp3"
  | "music/mystery loop 2.mp3"
  | "music/mystery loop 3.mp3"
  | "music/mystery loop 4.mp3"
  | "music/the void.mp3"
  | "music.json"
  | "npc.png"
  | "oberon_portrait.png"
  | "owo.png"
  | "tasukete_portrait.png"
  | "tileset.png"
  | "world.json"
  | "miranda_walk_0000.png"
  | "miranda_walk_0001.png"
  | "miranda_walk_0002.png"
  | "miranda_walk_0003.png"
  | "tasukete/tasukete_0000.png"
  | "tasukete/tasukete_0001.png"
  | "tasukete/tasukete_0002.png"
  | "tasukete/tasukete_0003.png"
  | "tasukete/tasukete_0004.png"
  | "tasukete/tasukete_0005.png"
  | "tasukete/tasukete_0006.png"
  | "tasukete/tasukete_0007.png"
  | "tasukete/tasukete_0008.png"
  | "tasukete/tasukete_0009.png"
  | "tasukete/tasukete_0010.png"
  | "tasukete/tasukete_0011.png"
  | "tasukete/tasukete_0012.png"
  | "tasukete/tasukete_0013.png"
  | "tasukete/tasukete_0014.png"
  | "tasukete/tasukete_0015.png"
  | "tasukete/tasukete_0016.png"
  | "tasukete/tasukete_0017.png"
  | "tasukete/tasukete_0018.png"



export const AssetsToLoad = {
  "bookshelf"            : { type: "Image"       as const, path: "bookshelf.png"              },
  "credits/credits"      : { type: "Image"       as const, path: "credits/credits.gif"        },
  "dialog"               : { type: "Image"       as const, path: "dialog.png"                 },
  "dialog_box"           : { type: "Image"       as const, path: "dialog_box.png"             },
  "interactions"         : { type: "TileMap"     as const, path: "interactions.json"          },
  "loop1"                : { type: "Audio"       as const, path: "loop1.mp3"                  },
  "loop2"                : { type: "Audio"       as const, path: "loop2.mp3"                  },
  "map"                  : { type: "TileMap"     as const, path: "map.json"                   },
  "miranda"              : { type: "Image"       as const, path: "miranda.png"                },
  "miranda_portrait"     : { type: "Image"       as const, path: "miranda_portrait.png"       },
  "music/credits"        : { type: "Audio"       as const, path: "music/credits.mp3"          },
  "music/mystery loop 1" : { type: "Audio"       as const, path: "music/mystery loop 1.mp3"   },
  "music/mystery loop 2" : { type: "Audio"       as const, path: "music/mystery loop 2.mp3"   },
  "music/mystery loop 3" : { type: "Audio"       as const, path: "music/mystery loop 3.mp3"   },
  "music/mystery loop 4" : { type: "Audio"       as const, path: "music/mystery loop 4.mp3"   },
  "music/the void"       : { type: "Audio"       as const, path: "music/the void.mp3"         },
  "music"                : { type: "TileMap"     as const, path: "music.json"                 },
  "npc"                  : { type: "Image"       as const, path: "npc.png"                    },
  "oberon_portrait"      : { type: "Image"       as const, path: "oberon_portrait.png"        },
  "owo"                  : { type: "Image"       as const, path: "owo.png"                    },
  "tasukete_portrait"    : { type: "Image"       as const, path: "tasukete_portrait.png"      },
  "tileset"              : { type: "Image"       as const, path: "tileset.png"                },
  "world"                : { type: "TileWorld"   as const, path: "world.json"                 },

  /* Animations */

  "miranda_walk": {
    type: "Animation" as const,
    paths: [
      "miranda_walk_0000.png",
      "miranda_walk_0001.png",
      "miranda_walk_0002.png",
      "miranda_walk_0003.png",
    ],
  },
  "tasukete/tasukete": {
    type: "Animation" as const,
    paths: [
      "tasukete/tasukete_0000.png",
      "tasukete/tasukete_0001.png",
      "tasukete/tasukete_0002.png",
      "tasukete/tasukete_0003.png",
      "tasukete/tasukete_0004.png",
      "tasukete/tasukete_0005.png",
      "tasukete/tasukete_0006.png",
      "tasukete/tasukete_0007.png",
      "tasukete/tasukete_0008.png",
      "tasukete/tasukete_0009.png",
      "tasukete/tasukete_0010.png",
      "tasukete/tasukete_0011.png",
      "tasukete/tasukete_0012.png",
      "tasukete/tasukete_0013.png",
      "tasukete/tasukete_0014.png",
      "tasukete/tasukete_0015.png",
      "tasukete/tasukete_0016.png",
      "tasukete/tasukete_0017.png",
      "tasukete/tasukete_0018.png",
    ],
  },
};

export const Assets = new TypesafeLoader(AssetsToLoad);
